export type { AnalysisResult, Point } from '../../modules/strip-cv/src/StripCv.types';
export { getAnalysisDecision, getAnalysisConfidence, deriveDetectedInterpretation } from '../../services/scanning/result-interpretation';
export type SessionInfo = { role: 'admin'|'guest'; owner: string; expiresAt: number };
export type Product = { label: string; batch: string; expiresAt: string; source: 'bundled'|'manual'|'qr' };
export const initialProduct: Product = { label:'Двухлинейная тест-полоска', batch:'Встроенный профиль', expiresAt:'',source:'bundled' };
export type AnalysisResponse = { analysis: import('../../modules/strip-cv/src/StripCv.types').AnalysisResult; width:number; height:number; product:Product };
export type ScanRecord = { id:string; owner:string; createdAt:number; date:string; photo:Blob; result:AnalysisResponse; configuration?:{qr:string;batch:string;flip:boolean}; confirmed:boolean; interpretation:'positive'|'negative'|null; manual:boolean; note:string };
export const reasonLabels: Record<string,string> = {
  learned_count_only:'Распознано число линий; измерение отношения T/C не выполняется', detector_no_proposal:'Не удалось найти тест-полоску', result_region_degenerate:'Область результата слишком мала', window_coverage_uncertain:'Область результата видна недостаточно уверенно', control_absent:'Контрольная линия не обнаружена', control_uncertain:'Контрольная линия недостаточно чёткая', test_uncertain:'Тестовая линия недостаточно чёткая', readers_do_not_confidently_agree:'Требуется проверка распознавания линий', spatial_test_absence_not_confirmed:'Не удалось уверенно определить число линий', window_readers_agree_on_coincident_peak:'Распознана одна контрольная линия', window_readers_and_spatial_absence_agree:'Распознана одна контрольная линия', readers_agree:'Распознаны две линии', invalid_model_evidence:'Недостаточно данных для уверенного распознавания',
  control_not_detected:'Контрольная линия не обнаружена', strip_not_found:'Тест-полоска не найдена', low_control_snr:'Контрольная линия недостаточно чёткая', blurry_image:'Снимок недостаточно резкий', excessive_glare:'Блики на изображении', low_confidence:'Недостаточная уверенность распознавания', insufficient_valid_pixels:'Недостаточно полезных пикселей', low_locator_confidence:'Проверьте границы тест-полоски', image_blurry:'Снимок недостаточно резкий', low_control_signal:'Слабый сигнал контрольной линии', clipped_pixels:'Часть снимка пересвечена', glare_detected:'Обнаружены блики', uncertain_peak_pair:'Требуется проверка положения линий', no_strip_candidate:'Не удалось найти тест-полоску',
};
export function qualityReason(code:string) { return reasonLabels[code] || `Проверка качества: ${code.replaceAll('_',' ')}`; }
