apply plugin: 'com.android.library'

group = 'expo.modules.smsretriever'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(':expo-modules-core').projectDir.absolutePath, 'ExpoModulesCorePlugin.gradle')
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()
useDefaultAndroidSdkVersions()

android {
  namespace 'expo.modules.smsretriever'
}

dependencies {
  implementation 'com.google.android.gms:play-services-auth-api-phone:18.2.0'
}
