import Link from "next/link";
import { ComparisonBars, RetentionHeatmap, RevenueChart, ScatterPlot } from "@/components/charts";
import { Icons } from "@/components/icons";
import { StudioShell } from "@/components/studio-shell";
import { Alert, Badge, Button, Checkbox, DataGrid, EmptyState, Field, IconButton, Input, ListRow, Metric, ModalDemo, PageHeader, Pagination, Panel, PopoverDemo, Progress, Radio, Section, Segmented, Select, Skeleton, Slider, Stepper, Switch, Tabs, Textarea, ToastDemo, Tooltip } from "@/components/ui";

const colors = [
  ["Canvas", "#ECEEF0", "canvas"], ["Surface", "#FFFFFF", "surface"], ["Chrome", "#F6F7F8", "chrome"], ["Text", "#1B1D1F", "text"],
  ["Muted", "#6D7278", "muted"], ["Border", "#D4D7DA", "border"], ["Active", "#0F766E", "accent"], ["Success", "#27835D", "success"],
  ["Warning", "#A46B13", "warning"], ["Danger", "#B84242", "danger"]
];

export default function KitPage() {
  return <StudioShell title="Pro Data UI Kit" inspector={false}>
    <div className="workspace-head"><div className="crumbs"><Link href="/">ArtificialLabs</Link><Icons.chevronRight size={11}/><strong>Design system</strong></div><div className="workspace-actions"><Badge tone="teal">v1.0</Badge><Button size="sm" icon={<Icons.download size={13}/>}>Tokens</Button></div></div>
    <div className="kit-scroll">
      <PageHeader eyebrow="ArtificialLabs admin design system" title="Pro Data Studio" description="A high-density interface system for serious analytical work. Native spatial logic, exact data alignment, and color used only when it communicates state." actions={<><Button icon={<Icons.grid size={14}/>}>Component index</Button><Link className="button button-primary button-md" href="/">Open dashboard <Icons.chevronRight size={13}/></Link></>}/>
      <div className="kit-stats"><span><strong>42</strong> reusable primitives</span><span><strong>4</strong> analytical charts</span><span><strong>3</strong> responsive panes</span><span><strong>AA</strong> focus contrast</span></div>

      <Section index="01" title="Foundation" description="Cold-neutral roles, compact system typography, and one-pixel structure. Every visible value below is a production token.">
        <div className="foundation-layout"><Panel title="Color roles" meta="10 semantic tokens"><div className="color-grid">{colors.map(([name, hex, token]) => <div className="color-item" key={name}><i className={`token-${token}`}/><span><strong>{name}</strong><code>{hex}</code></span></div>)}</div></Panel><Panel title="Typography" meta="System UI + SF Mono fallback"><div className="type-spec"><div><code>DISPLAY / 30 · 650</code><strong className="type-display">Operational clarity</strong></div><div><code>HEADING / 20 · 640</code><strong className="type-heading">Cohort analysis</strong></div><div><code>BODY / 13 · 450</code><span className="type-body">Measured language for dense professional interfaces.</span></div><div><code>LABEL / 10 · 650</code><span className="type-label">UPDATED 2 MIN AGO</span></div><div><code>DATA / 12 · 550</code><span className="type-data">$1,248,920.40 · +8.42%</span></div></div></Panel></div>
        <div className="token-grid"><Panel title="Spacing"><div className="spacing-spec">{[4,8,12,16,24,32].map(n=><div key={n}><i style={{width:n*1.5}}/><code>{n}</code></div>)}</div></Panel><Panel title="Radius"><div className="radius-spec"><i className="r0">0</i><i className="r3">3</i><i className="r5">5</i><i className="r8">8</i><i className="r99">Full</i></div></Panel><Panel title="Elevation"><div className="elevation-spec"><i>Rule</i><i>Panel</i><i>Float</i></div></Panel><Panel title="Motion"><div className="motion-spec"><span><i className="motion-fast"/>110ms feedback</span><span><i className="motion-state"/>180ms state</span><span><i className="motion-overlay"/>240ms overlay</span></div></Panel></div>
      </Section>

      <Section index="02" title="Core controls" description="Compact desktop controls grow on touch devices. Focus, pressed, loading, destructive, disabled, and validation states are explicit.">
        <div className="kit-columns"><Panel title="Buttons" meta="Action hierarchy"><div className="showcase-row"><Button variant="primary" icon={<Icons.bolt size={14}/>}>Run model</Button><Button icon={<Icons.upload size={14}/>}>Share</Button><Button variant="ghost" icon={<Icons.filter size={14}/>}>Filter</Button><Button variant="danger" icon={<Icons.error size={14}/>}>Remove</Button><Button loading variant="primary">Processing</Button><Button disabled>Disabled</Button></div><div className="icon-showcase"><Tooltip text="Pointer tool"><IconButton label="Pointer" active><Icons.pointer/></IconButton></Tooltip><Tooltip text="Add item"><IconButton label="Add"><Icons.plus/></IconButton></Tooltip><Tooltip text="Download"><IconButton label="Download"><Icons.download/></IconButton></Tooltip><Tooltip text="Settings"><IconButton label="Settings"><Icons.settings/></IconButton></Tooltip></div></Panel><Panel title="Selection" meta="Native interaction states"><div className="selection-grid"><div><Checkbox label="Include incomplete rows" defaultChecked/><Checkbox label="Show archived datasets"/><Checkbox label="Unavailable option" disabled/></div><div><Radio name="mode" label="Observed values" defaultChecked/><Radio name="mode" label="Forecast values"/><Radio name="mode" label="Both series"/></div><div><Switch label="Live updates" defaultOn/><Switch label="Normalize values"/><Stepper value={12}/></div></div></Panel></div>
        <div className="kit-columns"><Panel title="Form fields" meta="Default, help, error, textarea"><div className="form-grid"><Field label="Model name" hint="Visible to workspace members"><Input defaultValue="Revenue model"/></Field><Field label="Aggregation"><Select defaultValue="weekly"><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></Select></Field><Field label="Source key" error="Key must start with a letter"><Input defaultValue="2026-revenue" aria-invalid="true"/></Field><Field label="Description" hint="Optional · 280 characters"><Textarea defaultValue="Observed net revenue after refunds and fees."/></Field></div></Panel><Panel title="View controls" meta="Context switching"><div className="view-controls"><Tabs items={["Overview", "Segments", "Quality"]}/><Segmented items={["Table", "Chart", "Split"]} initial={2}/><Slider value={68}/></div></Panel></div>
      </Section>

      <Section index="03" title="Navigation" description="Navigation preserves place and context: command bar for tools, navigator for objects, tabs for local views, and compact pagination for datasets.">
        <div className="kit-columns nav-demo"><Panel title="Navigator pattern"><div className="mini-nav"><div className="navigator-search"><Icons.search size={13}/><input placeholder="Search"/><kbd>⌘F</kbd></div><ListRow icon={<Icons.chart size={14}/>} title="Revenue model" active trailing={<Badge tone="teal">Live</Badge>}/><ListRow icon={<Icons.table size={14}/>} title="Transactions" subtitle="124,893 rows"/><ListRow icon={<Icons.layers size={14}/>} title="Cohorts" subtitle="12 groups"/></div></Panel><Panel title="Path & pagination"><div className="navigation-stack"><div className="crumbs"><span>Workspace</span><Icons.chevronRight size={11}/><span>Models</span><Icons.chevronRight size={11}/><strong>Revenue</strong></div><Pagination/><div className="command-search"><Icons.search size={14}/><span>Search datasets and commands</span><kbd>⌘ K</kbd></div></div></Panel></div>
      </Section>

      <Section index="04" title="Data display" description="Data is the interface. Panels remain flat, numeric columns align, selection survives comparison, and status always includes a text label.">
        <div className="metric-strip kit-metrics"><Metric label="Net revenue" value="$5.44M" delta="↑ 6.8% period"/><Metric label="Gross margin" value="42.8%" delta="↑ 2.4 pts"/><Metric label="At-risk segments" value="2" delta="↓ 1 segment"/><Metric label="Coverage" value="99.4%" delta="↑ 0.2 pts"/></div>
        <Panel title="Data grid" meta="Selectable rows · sorted columns" actions={<div className="panel-actions"><Button size="sm" icon={<Icons.filter size={13}/>}>Filter</Button><IconButton label="Download"><Icons.download size={14}/></IconButton></div>}><DataGrid/></Panel>
        <div className="kit-three"><Panel title="Status & badges"><div className="badge-stack"><Badge dot>Draft</Badge><Badge tone="teal" dot>Active</Badge><Badge tone="success" dot>Healthy</Badge><Badge tone="warning" dot>Monitor</Badge><Badge tone="danger" dot>At risk</Badge></div></Panel><Panel title="Progress"><div className="progress-stack"><label>Coverage <b>99%</b></label><Progress value={99}/><label>Validation <b>84%</b></label><Progress value={84} tone="success"/><label>Sync <b>42%</b></label><Progress value={42} tone="warning"/></div></Panel><Panel title="Loading"><div className="skeleton-stack"><Skeleton width="38%" height={12}/><Skeleton/><Skeleton width="86%"/><div><Skeleton height={28}/><Skeleton height={28}/><Skeleton height={28}/></div></div></Panel></div>
      </Section>

      <Section index="05" title="Feedback" description="Feedback is restrained but unmistakable. Floating surfaces are the only elements allowed meaningful elevation.">
        <div className="feedback-grid"><div className="alert-stack"><Alert title="Model updated">All 18 segments passed validation.</Alert><Alert tone="success" title="Export complete">The CSV is ready in your downloads.</Alert><Alert tone="warning" title="Partial source delay">CRM data is 14 minutes behind.</Alert><Alert tone="danger" title="Connection failed">Warehouse credentials require attention.</Alert></div><Panel title="Floating feedback"><div className="floating-demo"><ToastDemo/><PopoverDemo/><ModalDemo/></div><div className="inline-error"><Icons.error size={13}/><span>Date range cannot end before it starts.</span></div></Panel></div>
        <div className="kit-columns"><Panel title="Empty state"><EmptyState/></Panel><Panel title="Dialog anatomy"><div className="dialog-preview"><span className="modal-icon"><Icons.warning size={18}/></span><div><strong>Recompute historical values?</strong><p>This affects 124,893 rows and may take several minutes.</p></div><div className="dialog-buttons"><Button size="sm">Cancel</Button><Button size="sm" variant="primary">Recompute</Button></div></div></Panel></div>
      </Section>

      <Section index="06" title="Analytical charts" description="Four dependency-free chart primitives with axes, legends, comparative context, and inspectable marks.">
        <div className="charts-grid"><Panel><RevenueChart/></Panel><Panel><ComparisonBars/></Panel><Panel><ScatterPlot/></Panel><Panel><RetentionHeatmap/></Panel></div>
      </Section>

      <Section index="07" title="Layout patterns" description="The kit supports the recurring structures of professional data work: three-pane studio, grid review, form inspector, and focused analysis.">
        <div className="layout-grid"><LayoutPreview kind="studio" title="Three-pane studio" note="Navigator, analytical canvas, property inspector"/><LayoutPreview kind="grid" title="Dataset review" note="Toolbar, filters, dense grid, status footer"/><LayoutPreview kind="detail" title="Focused analysis" note="Primary visualization with supporting evidence"/><LayoutPreview kind="form" title="Inspector form" note="Label/value pairs and staged actions"/></div>
      </Section>
    </div>
  </StudioShell>;
}

function LayoutPreview({ kind, title, note }: { kind: string; title: string; note: string }) {
  return <div className="layout-preview"><div className={`layout-wire wire-${kind}`}><header/><aside/><main><i/><i/><i/></main><footer/></div><strong>{title}</strong><span>{note}</span></div>;
}
