import {test,expect,type Page} from '@playwright/test';
import sharp from 'sharp';
import {createSession,createLink} from '../lib/auth';
const base='http://127.0.0.1:3040';
test('configured credentials authenticate through the login form',async({page})=>{
 test.skip(!process.env.CV_DEMO_TEST_PASSWORD,'Set CV_DEMO_TEST_PASSWORD to verify the configured demo password.');
 await page.goto('/');
 await page.getByLabel('Логин',{exact:true}).fill('admin');
 await page.getByLabel('Пароль',{exact:true}).fill(process.env.CV_DEMO_TEST_PASSWORD!);
 await page.getByRole('button',{name:'Продолжить',exact:true}).click();
 await expect(page.getByRole('button',{name:'Начать сканирование',exact:true})).toBeVisible();
 await page.reload();
 await expect(page.getByRole('button',{name:'Начать сканирование',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Выйти',exact:true}).click();
 await expect(page.getByRole('dialog',{name:'Вход в Сфера Scan'})).toBeVisible();
});
async function authenticated(page:Page){const {token}=createSession('admin');await page.context().addCookies([{name:'cv_demo_session',value:token,url:base,httpOnly:true,sameSite:'Lax'}]);await page.goto('/');await expect(page.getByRole('button',{name:'Начать сканирование',exact:true})).toBeVisible();}
test('login gate, auth and origin protection',async({page,request})=>{await page.goto('/');await expect(page.getByRole('dialog',{name:'Вход в Сфера Scan'})).toBeVisible();await page.getByLabel('Логин',{exact:true}).fill('admin');await page.getByLabel('Пароль',{exact:true}).fill('invalid');await page.getByRole('button',{name:'Продолжить'}).click();await expect(page.getByRole('alert')).toBeVisible();expect((await request.post('/api/analyze',{headers:{Origin:base}})).status()).toBe(401);expect((await request.post('/api/auth',{headers:{Origin:'https://wrong.example'},data:{}})).status()).toBe(403);await page.screenshot({path:'test-results/login.png'});});
test('instructions, real blank-image CV, history and manual boundaries',async({page})=>{await authenticated(page);await page.screenshot({path:'test-results/desktop.png',fullPage:true});await page.getByRole('button',{name:'Загрузить фото',exact:true}).click();await expect(page.getByRole('heading',{name:'Подготовьте ёмкость'})).toBeVisible();await page.getByLabel('Больше не показывать инструкцию').check();for(let i=0;i<4;i++)await page.getByRole('button',{name:'Продолжить',exact:true}).click();await page.getByRole('button',{name:'К сканированию',exact:true}).click();await page.getByLabel('Номер партии').fill('SYNTHETIC-01');await page.getByRole('button',{name:'Продолжить',exact:true}).click();const buffer=await sharp({create:{width:800,height:400,channels:3,background:'#dddddd'}}).png().toBuffer();await page.getByLabel('Загрузить снимок теста',{exact:true}).setInputFiles({name:'synthetic.png',mimeType:'image/png',buffer});await page.getByRole('button',{name:'Распознать',exact:true}).click();await expect(page.getByRole('heading',{name:'Нужен более чёткий снимок'})).toBeVisible();await expect(page.getByRole('button',{name:'Сохранить результат',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Уточнить границы',exact:true}).click();await page.getByRole('slider',{name:'Угол 1',exact:true}).focus();await page.keyboard.press('ArrowRight');await page.getByRole('button',{name:'Повторить анализ',exact:true}).click();await expect(page.getByRole('heading',{name:'Нужен более чёткий снимок'})).toBeVisible();await page.getByRole('button',{name:'Сохранить для проверки',exact:true}).click();await expect(page.getByRole('button',{name:'Сохранено в истории'})).toBeVisible();await page.screenshot({path:'test-results/result.png',fullPage:true});await page.getByRole('button',{name:'История',exact:true}).click();await expect(page.getByText('Требует проверки',{exact:true})).toBeVisible();await page.reload();await page.getByRole('button',{name:'История',exact:true}).click();await page.getByRole('button').filter({hasText:'Требует проверки'}).click();await page.getByRole('button',{name:'Удалить сканирование'}).click();await page.getByRole('button',{name:'Удалить',exact:true}).click();await expect(page.getByRole('heading',{name:'Пока нет сканирований'})).toBeVisible();});
test('mobile layout and passwordless link revocation',async({page,browser})=>{await page.setViewportSize({width:390,height:844});await authenticated(page);await page.screenshot({path:'test-results/mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.getByRole('button',{name:'Ссылки доступа',exact:true}).click();await page.getByLabel('Название',{exact:true}).fill('E2E invitation');await page.getByRole('button',{name:'Создать',exact:true}).click();const url=await page.getByLabel('Сохраните ссылку — она показывается один раз').inputValue();const context=await browser.newContext();const guest=await context.newPage();await guest.goto(url);await expect(guest.getByRole('button',{name:'Начать сканирование',exact:true})).toBeVisible();await expect(guest.getByRole('button',{name:'Ссылки доступа'})).toHaveCount(0);expect((await context.request.get(base+'/api/links')).status()).toBe(403);await page.locator('.link-row').filter({hasText:'E2E invitation'}).getByRole('button',{name:'Отозвать'}).click();await guest.reload();await expect(guest.getByRole('dialog',{name:'Вход в Сфера Scan'})).toBeVisible();await context.close();});
