"""Synthetic fixtures only. Generated bytes stay in ignored output/pdf/."""
from pathlib import Path
import json
from PIL import Image, ImageDraw, ImageFont, ImageFilter
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from pypdf import PdfReader, PdfWriter

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "output/pdf/document-ocr"
OUT.mkdir(parents=True, exist_ok=True)
FONT = "/System/Library/Fonts/Supplemental/Arial.ttf"
pdfmetrics.registerFont(TTFont("Fixture", FONT))
LINES = ["СИНТЕТИЧЕСКИЙ ОБРАЗЕЦ - НЕ МЕДИЦИНСКИЙ РЕЗУЛЬТАТ", "Дата: 2026-09-11", "Образец A; 1,25; ед/л; 0,50-2,00", "SYNTHETIC SAMPLE - NOT A MEDICAL RESULT", "Sample B; 12.50; units/L; 10.00-15.00"]

def make_pdf(name, pages):
    doc = canvas.Canvas(str(OUT / name), pagesize=(595, 842), pageCompression=1)
    for page in range(pages):
        doc.setFont("Fixture", 14)
        for index, line in enumerate(LINES):
            doc.drawString(30, 785 - index * 40, line)
        doc.drawString(30, 80, f"Page {page + 1}")
        doc.showPage()
    doc.save()

make_pdf("two-pages.pdf", 2)
make_pdf("twenty-pages.pdf", 20)
make_pdf("too-many-pages.pdf", 21)
image = Image.new("RGB", (2200, 1500), "white")
draw = ImageDraw.Draw(image)
font = ImageFont.truetype(FONT, 48)
for index, line in enumerate(LINES):
    draw.text((60, 120 + index * 140), line, font=font, fill="black")
image.save(OUT / "sample.png")
image.save(OUT / "sample.jpg", quality=93)
variants = Image.new("RGB", (2200, 1500), "white")
variant_draw = ImageDraw.Draw(variants)
for index, line in enumerate([
    "SYNTHETIC LAB TABLE / СИНТЕТИЧЕСКАЯ ТАБЛИЦА",
    "Дата взятия / Collection date: 2026-09-11",
    "Test | Result | Units | Reference",
    "Protein | negative | | negative",
    "Образец C | <0,10 | ед/л | <0,50",
    "Дата взятия / Collection date: 2026-09-12",
    "Образец D | отрицательно | | отрицательно",
    "Sample E | ≥2.50 | units/L | ≥1.00",
]):
    variant_draw.text((60, 70 + index * 150), line, font=font, fill="black")
variants.save(OUT / "lab-variants.jpg", quality=95)
Image.new("RGB", (1600, 1200), "white").save(OUT / "blank.jpg", quality=95)
rotated = image.rotate(90, expand=True)
rotated.save(OUT / "rotated.png")
image.resize((550, 375)).filter(ImageFilter.GaussianBlur(1.2)).save(OUT / "poor-quality.jpg", quality=35)
reader = PdfReader(str(OUT / "two-pages.pdf"))
writer = PdfWriter()
for page in reader.pages:
    writer.add_page(page)
writer.encrypt("synthetic-fixture-password")
with (OUT / "password.pdf").open("wb") as target:
    writer.write(target)
(OUT / "corrupt.pdf").write_bytes(b"%PDF-1.7\ncorrupt synthetic fixture\n")
(OUT / "unsupported.txt").write_text("Synthetic unsupported plain-text document. Not medical data.\n", encoding="utf8")
with (OUT / "too-large.pdf").open("wb") as target:
    target.write(b"%PDF-1.7\n")
    target.seek(20 * 1024 * 1024)
    target.write(b"x")
(OUT / "expected.json").write_text(json.dumps({"synthetic": True, "tokens": ["1,25", "12.50", "2026-09-11"], "pages": 2, "clinicalAccuracyClaim": False}, ensure_ascii=False, indent=2), encoding="utf8")
print("Synthetic OCR fixtures generated in output/pdf/document-ocr; no clinical accuracy claim.")
